[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
lock = "asrMFZq2j6bA1RADnGM58txGVtSzMcDxxSVr57mQhLZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
