[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
asr = "ASRwFhKHjzF96q6BAvWcjCQQT8WpBU9XTkWDKe5ttmUX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://rpc.testnet.soo.network/rpc"
#cluster = "localnet"
wallet = "~/.config/solana/soon.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
