pub const DISCRIMINATOR_LENGTH: usize = 8;
pub const PUBLIC_KEY_LENGTH: usize = 32;
pub const TIMESTAMP_LENGTH: usize = 8;
pub const STRING_LENGTH_PREFIX: usize = 4;
pub const VECTOR_LENGTH_PREFIX: usize = 4;
pub const BUMP_LENGTH: usize = 1;
pub const BOOL_LENGTH: usize = 1;
pub const MAX_LOCKER_NAME_LENGTH: usize = 50 * 4;
pub const MAX_TITLE_LENGTH: usize = 50 * 4;
pub const MAX_SYMBOL_LENGTH: usize = 10 * 4;
pub const MAX_CONTENT_LENGTH: usize = 280 * 4; // 280 chars max.
                                               // pub const ONE_DAY_IN_SECONDS: i64 = 5;
pub const ONE_DAY_IN_SECONDS: i64 = 86400;
pub const ONE_WEEK_IN_SECONDS: i64 = ONE_DAY_IN_SECONDS * 7;
pub const ONE_YEAR_IN_SECONDS: i64 = ONE_WEEK_IN_SECONDS * 52;
pub const ONE_MONTH_IN_SECONDS: i64 = ONE_DAY_IN_SECONDS * 3; // three days for devnet
                                                              // pub const ONE_MONTH_IN_SECONDS: i64 = 5;
                                                              //pub const THREE_MONTH_IN_SECONDS: i64 = ONE_MONTH_IN_SECONDS * 3; // localnet
pub const THREE_MONTH_IN_SECONDS: i64 = ONE_MONTH_IN_SECONDS; // 3 days season duration on devnet
